#!/usr/bin/env bash
#Display the content of /etc/passwd,tell the story of passwd

while IFS=":" read -r 1 2 3 4 5 6 7;
do
 echo "The user $1 is part of the $4 gang, lives in $6 and rides $7. $3's place is protected by the passcode $2, more info about the user here: $5"

done < /etc/passwd

