#!/usr/bin/env bash
#Displays Best School 10 times but on the 9th it displays Best school then Hi on a new line
n=1
while [ $n -le 9 ]
do 
  echo "Best School"
  ((n++))
  if [ $n -eq 9 ]
  then 
  printf "Best School \nHi\n"
  fi
done
