#!/usr/bin/env bash
#displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)

files=$(ls)

for name in $files
do
	echo "$name" | cut -d'-' -f2-
done
