#!/usr/bin/env bash
#Does a lot
file=/var/run/myscript.pid
echo "$$" > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm -r $file; exit' SIGTERM
trap "echo Y U no love me?!"SIGINT
echo "rm -r $file; exit" SIGQUIT SIGTERM 

 count=0
while [ $count == 0 ]
do
  echo "To infinity and beyond"
done
